In [ ]:
# 1. Load the StudentsPerformance.csv dataset using Pandas and display the first 10 rows.
# 2. Display the number of rows and columns in the dataset using Pandas.
# 3. Display all column names and check whether the dataset contains any missing values.
# 4. Find the average, maximum, and minimum math scores using Pandas and NumPy.
# 5. Count how many male and female students are present in the dataset.
# 6. Find the average reading score of students based on their gender.
# 7. Filter and display all students who scored more than 80 marks in mathematics.
# 8. Count how many students completed the test preparation course and how many did not.
# 9. Calculate the average math, reading, and writing scores for all students using NumPy.
# 10. Find and display the top 10 students with the highest writing scores using Pandas.

In [1]:
# Q1
from google.colab import files
uploaded = files.upload()

Saving StudentsPerformance.csv to StudentsPerformance.csv

In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv('StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [23]:
# Q2
df.shape

(1000, 8)

In [7]:
# Q3
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [20]:
# Q4 overall way vs single way
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [24]:
#single way
df['math score'].mean()

100

In [25]:
df['math score'].min()

0

In [26]:
df['math score'].max()

100

In [27]:
# Q5
df['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [28]:
# Q6
df.groupby('gender')['reading score'].mean()

gender
female    72.608108
male      65.473029
Name: reading score, dtype: float64

In [33]:
# Q7
data = df[df['math score']> 80]
data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
...,...,...,...,...,...,...,...,...
979,female,group C,associate's degree,standard,none,91,95,94
981,male,group D,some high school,standard,none,81,78,78
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95

In [37]:
# Q8
df['test preparation course'].value_counts()

test preparation course
none         642
completed    358
Name: count, dtype: int64

In [38]:
# Q9
np.mean(df['math score'])

np.float64(66.089)

In [39]:
np.mean(df['reading score'])

np.float64(69.169)

In [40]:
np.mean(df['writing score'])

np.float64(68.054)

In [42]:
# Q10
data1= df.sort_values(
    by="writing score",
    ascending=False
).head(10)
data1

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
458,female,group E,bachelor's degree,standard,none,100,100,100
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
403,female,group D,high school,standard,completed,88,99,100
377,female,group D,master's degree,free/reduced,completed,85,95,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
685,female,group E,master's degree,standard,completed,94,99,100
106,female,group D,master's degree,standard,none,87,100,100